### ISSUE TITLE
CopyDirect is not working in Sketch52.3(67297)

### ISSUE THREAD

**Issue by ysjn** [SudevKiyada/paste-direct#1]
Hi, thanks for great plugin!

It seems copy direct is not working in Sketch52.3(67297).
Please look in to it when you have time.

Cheers.

**Comment by SudevKiyada** [comment]
Hello @ysjn,

Thanks for using PasteDirect ! I checked it on 52.3 and it's working perfectly fine for me. Please check if any other plugin is overriding the shortcut for Copy Direct. Right now, CopyDirect is supporting only layers. Text are yet to be integrated.

Hope this solves the problem. Revert back if the problem still persists.

Regards.

**Comment by ysjn** [comment]
Hi @SudevKiyada,
You are right, the plugin was working perfectly fine.

Sorry I wasn't reading the document well enough, I was expecting the Copy Direct command to copy original text from text layers. Current behavior is super useful too!

Idk if this plugin should be able to copy text directly, since your aim is to copy layer's attributes (e.g. color values). But having option to copy text directly will sure be useful. Please consider implementing it. 😉

My problem is solved, closing issue.
Thanks!

**Comment by SudevKiyada** [comment]
Sure @ysjn ! Will look into it for the next update.
